name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node-version}}

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: install modules
        run: pnpm install
      - name: run playwright
        run: pnpm run test
      - name: run unit
        run: pnpm run test:unit