name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{matrix.node-version}}

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: install modules
        run: pnpm install

      - name: run unit
        run: pnpm run test:unit

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30